import { AgentSkill } from "../../harness/index.ts";

export const CreateStudyArtifactsSkill = AgentSkill.make({
  name: "create-study-artifacts",
  description: "Create and manage study artifacts: markdown notes, quizzes, tests, submissions, and graded attempts.",
  content: [
    "# Create study artifacts",
    "",
    "Use this skill when the user asks you to create study notes, quizzes, tests, or practice submissions. For visual summaries (esquema, mapa, diagrama) load `teach-visually` instead; for an explanation objective (the student explains a topic in their own words and is corrected point by point) load `assess-explanations`.",
    "",
    "Artifacts are persisted study objects:",
    "- `note`: title plus markdown content. Notes are not submitted or graded.",
    "- `quiz`: title plus auto-gradable multiple-choice / true-false questions.",
    "- `test`: title plus questions. Tests may include multiple-choice, true-false, and short-answer questions.",
    "- `diagram`: a visual summary of related concepts anchored to pages; its rules live in the `teach-visually` skill.",
    "- `explain`: key points the student must explain in their own words, with hidden references; its rules live in the `assess-explanations` skill.",
    "",
    "Available CLI commands:",
    "- `artifacts list [note|quiz|test|diagram|explain]`: list saved artifacts.",
    "- `artifacts show <artifactId>`: show an artifact JSON.",
    "- `artifacts create '<json>'`: create a note, quiz, or test from CreateArtifactInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts submit '<json>'`: submit answers for a quiz or test from SubmitAttemptInput JSON. Always wrap JSON in single quotes.",
    "- `artifacts attempts [artifactId]`: list attempts.",
    "- `artifacts grade <attemptId>`: grade and persist a submitted attempt.",
    "",
    "CreateArtifactInput examples:",
    "- `artifacts create '{\"kind\":\"note\",\"title\":\"Derivatives summary\",\"markdown\":\"# Derivatives\\n...\"}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Basics quiz\",\"questions\":[{\"type\":\"true-false\",\"id\":\"q1\",\"prompt\":\"2+2=4\",\"correctAnswer\":true,\"explanation\":\"Basic arithmetic.\"}]}'`",
    "- `artifacts create '{\"kind\":\"quiz\",\"title\":\"Concept quiz\",\"questions\":[{\"type\":\"multiple-choice\",\"id\":\"q1\",\"prompt\":\"Which option is qualitative?\",\"options\":[{\"id\":\"qualitative\",\"text\":\"Qualitative\"},{\"id\":\"quantitative\",\"text\":\"Quantitative\"}],\"correctOptionId\":\"qualitative\",\"explanation\":\"Qualitative data describes qualities.\"}]}'`",
    "",
    "Provenance:",
    "- When the artifact is based on uploaded material, include `\"source\":{\"materialId\":\"<id>\",\"pages\":[1,2]}` with the pages you actually rendered. It lets the student and the system trace what the artifact covers.",
    "",
    "Multiple-choice question rules:",
    "- `options` must be objects, not strings: `{\"id\":\"a\",\"text\":\"Option text\"}`.",
    "- `correctOptionId` must exactly match one option `id`.",
    "",
    "SubmitAttemptInput example:",
    "- `artifacts submit '{\"artifactKind\":\"quiz\",\"artifactId\":\"<id>\",\"answers\":[{\"questionType\":\"true-false\",\"questionId\":\"q1\",\"answer\":true}]}'`",
    "",
    "Workflow:",
    "1. For artifacts based on uploaded materials, inspect the uploaded material first.",
    "2. Create a compact artifact that directly matches the user's request.",
    "3. Use stable question ids like `q1`, `q2`, `q3`.",
    "4. For quizzes, prefer true-false and multiple-choice because grading is deterministic.",
    "5. When a user submits answers, save the attempt and then grade it.",
    "",
    "After creating an artifact:",
    "- The interface shows it in the student's panel, where they solve it. Do not repeat its questions, options or content in the chat.",
    "- Reply with two or three sentences: what you created (kind, title, number of questions, which material pages it covers) and an invitation to open it from the panel.",
    "- If the student asks about a question afterwards, refer to it by its number and explain; do not reveal correct answers of an unanswered quiz."
  ].join("\n")
});
